### PR TITLE
Use first framework

### LINKED ISSUE #5: Error during a build with createPodspecGenerationTask() method
KotlinCocoapods v0.9

> Caused by: java.lang.IllegalArgumentException: Collection has more than one element.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:506)
	at co.touchlab.kotlin.gradle.plugin.cocoapods.KotlinCocoapodsPlugin.createPodspecGenerationTask(KotlinCocoapodsPlugin.kt:170)
	at co.touchlab.kotlin.gradle.plugin.cocoapods.KotlinCocoapodsPlugin.access$createPodspecGenerationTask(KotlinCocoapodsPlugin.kt:46)
	at co.touchlab.kotlin.gradle.plugin.cocoapods.KotlinCocoapodsPlugin$apply$$inlined$with$lambda$1$1.execute(KotlinCocoapodsPlugin.kt:270)
	at co.touchlab.kotlin.gradle.plugin.cocoapods.KotlinCocoapodsPlugin$apply$$inlined$with$lambda$1$1.execute(KotlinCocoapodsPlugin.kt:46)

Maybe it's related to that I have two native apple targets..iOS and tvOS

### PR DESCRIPTION
**Pull request by samhill303**
Get the framework from the first target rather than using single(). There may be multiple supported targets. We can grab just the first because we configure the framework the same for every supported target

### CODE REVIEW

File: gradle-plugin/src/main/kotlin/co/touchlab/kotlin/gradle/targets/native/tasks/CocoapodsTasks.kt [hunk 1]
```diff
@@ -32,14 +32,14 @@ open class PodspecTask : DefaultTask() {
...
 
-    @Input
-    val frameworkNameProvider: Provider<String> = project.provider { framework.baseName}
+    @get:Input
+    lateinit var frameworkName:String
 
-    @get:Nested
-    internal lateinit var settings: CocoapodsExtension
+    @get:Input
+    var isStatic:Boolean = true
```
Comment (kpgalligan) [inline gradle-plugin/src/main/kotlin/co/touchlab/kotlin/gradle/targets/native/tasks/CocoapodsTasks.kt]: It looks like you shouldn't set these directly, but they're public. I don't want to hold up this PR, but at some point I'd like to think about that.
